# SPDX-License-Identifier: GPL-2.0-only
KBUILD_CFLAGS += -fsanitize=fuzzer-no-link
obj-$(CONFIG_B43)		+= b43/
obj-$(CONFIG_B43LEGACY)		+= b43legacy/

obj-$(CONFIG_BRCMFMAC)	+= brcm80211/
obj-$(CONFIG_BRCMSMAC)	+= brcm80211/
